### ISSUE TITLE
Cannot run Android tests

### ISSUE THREAD

**Issue by skychiarottoa** [CircleCI-Public/android-orb#20]
Hi we are running android tests (UI test) succesfully using circle ci with a Medium machine.
We try to use your orb in order to clean up the .circleci/config.yml file but we get the following error:
![image](https://user-images.githubusercontent.com/51656240/114169685-2ac68580-9932-11eb-949b-97d7177d14fd.png)

New config.yml file:
![image](https://user-images.githubusercontent.com/51656240/114172593-22704980-9936-11eb-9af9-025e4e1aea54.png)

thanks for your help

**Comment by lokst** [comment]
@skychiarottoa Glad to hear that you were able to run the UI tests successfully initially. It seems to me there may be some differences between your original config without the orb and the current config with the orb, that might be causing the difference in build result. Would you like to share a link to the last successful build before using the orb, so that we can try to spot what the differences are?

**Comment by skychiarottoa** [comment]
Hi,
thanks for your reply, I have attached the config file without orb.

[config_without_orb.yml.txt](https://github.com/CircleCI-Public/android-orb/files/6285620/config_without_orb.yml.txt)

**Comment by lokst** [comment]
@skychiarottoa Thanks for the config. Here are some thoughts after reviewing it:
1) Regarding the error when using the orb, do you consistently get it if you retry the build many times?
2) Could you try using the `additional-emulator-args` parameter and specifying `-skin 384x780` as I see that that parameter is present in the config that doesn't use the orb
3) Could you try specifying `post-emulator-wait-steps` and running `adb shell input keyevent 82` and ` adb shell settings put secure long_press_timeout 1500` in the steps? (As I see that those commands are run in the config that doesn't use the orb)

**Comment by skychiarottoa** [comment]
Yes I always get that error, I couldn't run any tests after several trials. I know that those args (skin etc) are not present right now but they don't influence the boot of the android emulator.

**Comment by skychiarottoa** [comment]
Can you write me the right syntax please?

![image](https://user-images.githubusercontent.com/51656240/114405012-8a2ccb80-9ba6-11eb-81f0-ea842e8f2267.png)

**Comment by skychiarottoa** [comment]
It seems to work but it slower. Maybe it is due to the "underlying" machine since I get the following error:
Too long with no output (exceeded 50m0s): context deadline exceeded

**Comment by lokst** [comment]
@skychiarottoa I think it might be hard to troubleshoot this without the links to the last working build and the failed build. Would you like to provide the build links here or alternatively open a support ticket at https://support.circleci.com/hc/en-us/requests/new ?

**Comment by felicianotech** [comment]
Closing this due to a lack of response. We have v2 of this orb coming out this week. If the problem persist with v2, please let us know and we can re-open this Issue.
