### ISSUE TITLE
Google play services not available after upgrading 

### ISSUE THREAD

**Issue by kmadsen** [CircleCI-Public/android-orb#25]
### Orb version

``` config.yml
version: 2.1
orbs:
  android: circleci/android@1.0.3

...
jobs:
  android-test:
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew android-auto:connectedDebugAndroidTest
          system-image: system-images;android-30;google_apis;x86
      - run:
          name: Save test results
          command: |
            mkdir -p ~/mapbox_test/
            adb pull sdcard/Download/mapbox_test ~/mapbox_test/
          when: on_fail
      - store_artifacts:
          path: ~/mapbox_test/

```

### What happened

We are updating our compile version to 30 in an app. But a test checking for `isGooglePlayServicesAvailable` started failing after this upgrade.

``` build.gradle
android {
-    compileSdkVersion(29)
+    compileSdkVersion(30)

    defaultConfig {
        applicationId = "com.mapbox.app"
        minSdkVersion(23)
-        targetSdkVersion(29)
+       targetSdkVersion(30)
}
```

``` kotlin
class LocationEngineProviderTest {

    @Test
    fun checkGooglePlayServicesAvailable() {
        val activityScenario = launchActivity<NavigationTestActivity>()
        activityScenario.onActivity { activity ->
            Assert.assertEquals(
                "Google location services have to be available",
                ConnectionResult.SUCCESS,
                GoogleApiAvailability.getInstance().isGooglePlayServicesAvailable(activity)
            )
        }
    }
}
```

### Expected behavior

The `LocationEngineProviderTest` should pass because we want to test integrations with google play services

**Comment by ryanbourdais** [comment]
Hi @kmadsen, as this issue is from over 6 months ago, does this issue still affect your project? If not, can you explain how/when it was resolved?

**Comment by kelvintaywl** [comment]
Hi @ryanbourdais this is still relevant for one of our customers (I can share the support ticket with you).
We are seeing the same issue when using `system-images;android-30;google_apis;x86` system image.

```
com.google.android.gms.common.api.ApiException: 17: API: LocationServices.API is not available on this device. Connection failed with: ConnectionResult{statusCode=SERVICE_INVALID, resolution=null, message=null}
```

**Comment by JalexChen** [comment]
This should be a permissions issue that was updated in the docs:

https://circleci.com/developer/machine/image/android

Specifically, this is the Android documentation outlining the differences from API level 29 to API Level 30: [docs](https://developer.android.com/training/location/permissions)

Going to close this out. @kmadsen - please reopen if you are still running into issues here

**Comment by kmadsen** [comment]
Hi! Sorry, another developer fixed this in our project so I never posted an update here.

Our fix was to not use `google_apis` but to use `google_apis_playstore`

```
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-30;google_apis_playstore;x86
```
