### ISSUE TITLE
Cannot install NDK v23 and after

### ISSUE THREAD

**Issue by guillaume-tgl** [CircleCI-Public/android-orb#28]
### Orb version

1.0.3

### What happened

I tried to upgrade the NDK version to r23b but it failed with error: `curl: (22) The requested URL returned error: 404 Not Found`.
The URL used to install the NDK is: https://dl.google.com/android/repository/android-ndk-r23b-linux-x86_64.zip

### Expected behavior

The URL should be https://dl.google.com/android/repository/android-ndk-r23b-linux.zip

**Comment by gmemstr** [comment]
It looks like very recently Google dropped the `x86_64` suffix from the files. I think we can do the same in this case and mark it as a minor version to avoid breakages for those pinned to it.

**Comment by guillaume-tgl** [comment]
Seems to be fixed since v2
