### ISSUE TITLE
`circleci/android:api` images depreciation

### ISSUE THREAD

**Issue by TrebuhD** [CircleCI-Public/android-orb#29]
Hello,

It seems like the `circleci/android:api-<version>` images that this orb uses will be getting deprecated by CircleCI on December 31st.

Sources:
https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/
https://circleci.com/developer/images/image/cimg/android

This should probably be migrated to use the new `cimg/android` images.

**Comment by felicianotech** [comment]
Thank you for this. This has been addressed with v2 of the Android orb.
