### ISSUE TITLE
android orb version 1 was able to digest and use matrix job parameters, now fails with The value of `name` must be a string

### ISSUE THREAD

**Issue by jkzilla** [CircleCI-Public/android-orb#38]
### Orb version
2.0.3
### What happened

android orb version 1 was able to digest and use matrix job parameters in the run ui tests step (### Expected behavior)
      - android/run-ui-tests:
          matrix:
            parameters:
              system-image:
                - system-images;android-30;default;x86_64
               #- system-images;android-31;default;x86_64 // Test with newest release
          name: "Test Android UI: <<matrix.system-image>>"

now fails with:
```
circleci config validate
Error: Error calling workflow: 'build_test_deploy'
Error calling job: 'android/run-ui-tests'
Unexpected executor invocation format
The value of `name` must be a string
Examples of correct executor invocation:
  executor: string-executor-name
  executor: {name: string-executor-name}
  executor: << parameters.executor-type-parameter >>
```

**Comment by KyleTryon** [comment]
Hello @jkzilla 

We have a current usage example showcasing how to use the matrix feature here: https://circleci.com/developer/orbs/orb/circleci/android#usage-test-matrix

The example you shared is a little misformatted in the markdown but we believe there may be an issue with this line:
`name: "Test Android UI: <<matrix.system-image>>"`

It may be that the `:` or the following space are not allowed.

If you are able, please share the CircleCI pipeline where this issue occurred or a reproducible config.

**Comment by marboledacci** [comment]
There hasn't been any update on this for a long time, I'm closing this.
