### ISSUE TITLE
Save-grade-cache command fails when /tmp/gradle_cache_seed file does not exists.

### ISSUE THREAD

**Issue by kelvintaywl** [CircleCI-Public/android-orb#40]
### Orb version

2.0.3

### What happened

The `save-gradle-cache` command expects a _/tmp/gradle_cache_seed_ file to exist, to generate a cache key.
https://github.com/CircleCI-Public/android-orb/blob/cbdf1508a6b2bcae9368f0af8227b78f52c08cea/src/commands/save-gradle-cache.yml#L11

I am not sure the rationale for this hardcoded value, but for builds where this file is not existing, the command will fail.
This can affect using the `start-emulator-and-run-tests` command as well, since [it calls on the `save-gradle-cache` command by default](https://github.com/CircleCI-Public/android-orb/blob/cbdf1508a6b2bcae9368f0af8227b78f52c08cea/src/commands/start-emulator-and-run-tests.yml#L222-L226).

### Expected behavior

Perhaps allow this file to be configurable, via a parameter?

**Comment by kelvintaywl** [comment]
hi @ryanbourdais thanks for the explanation!

I understand indeed then that the hardcoded value there is assumed that the job using this `save-gradle-cache` command **will also** use the Orb's `restore-gradle-cache` then.
My earlier ask was since i did not notice the `start-emulator` command explicitly calls `restore-gradle-cache`!
https://github.com/CircleCI-Public/android-orb/blob/cbdf1508a6b2bcae9368f0af8227b78f52c08cea/src/commands/start-emulator.yml#L174

We can close this issue i believe! Thanks for the explanation 🙏 

Although I would also like to know why the `save-gradle-cache` command is also not included in `start-emulator` but outside of it?

**Comment by ryanbourdais** [comment]
hi @kelvintaywl I will close this issue and move onto [this issue](https://github.com/CircleCI-Public/android-orb/issues/49) I believe that save-gradle-cache is separate so that users can choose whether they want to save the cache or not, as restore will just return exit code 0 if there is no cache to restore.
