### ISSUE TITLE
Restore Gradle Cache Test

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/android-orb#51]
We should test what PR #50 fixes. Setting a default and not should be tested.

**Comment by ryanbourdais** [comment]
@EricRibeiro we had a conversation yesterday in the images meeting about adding an explicit test to restore_gradle_cache because currently
its only called by other commands with overrides to the default parameter value. So there is no case that it runs in its default state

**Comment by ryanbourdais** [comment]
@EricRibeiro you're right that one isn't overriden, I must have overlooked it when I was checking yesterday. I'm now extra confused on how the error wasn't caught in testing.

**Comment by EricRibeiro** [comment]
> I'm now extra confused on how the error wasn't caught in testing.

The author mentioned this in #49:

> I also observed that, for [the "test-emulator-commands" job](https://app.circleci.com/pipelines/github/CircleCI-Public/android-orb/329/workflows/69cb4086-8d3f-4799-8090-13cf6b6fdafb/jobs/4688) triggered from PR https://github.com/CircleCI-Public/android-orb/pull/48, it somehow did not pick up the code changes from https://github.com/CircleCI-Public/android-orb/pull/48 and this ran fine;
It was running with the restore-gradle-cache command from v2.1.0 instead.
We can see this under the config, when clicking on "Compiled":
https://app.circleci.com/projects/github/CircleCI-Public/android-orb/config/?branchName=&pipelineNumber=329

I am not sure what caused the issue above, but it's the reason the tests didn't pick up the error.

**Comment by felicianotech** [comment]
Just going to close this for now. Not sure what to do with this at the moment and there hasn't been any customer complaints.
