### ISSUE TITLE
How can attach screenshots of ui test executions with android/start-emulator-and-run-tests command?

### ISSUE THREAD

**Issue by skychiarottoa** [CircleCI-Public/android-orb#54]
### circleci/android@2.1.2

Before adopting this orb in order to attach screenshoot of our ui tests we run the following commands:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/51656240/180718967-a35753d1-813a-4237-aa2e-36bb766d1c48.png">

Now we cannot run "adb pull" while it is still running since "adb "is started and killed inside the command: start-emulator-and-run-tests command

How can we attach screenshot images to the "CI's Artifacts" tab?
It is possible to add a parameter to  start-emulator-and-run-tests ? Something like
**adb_pull_destination_folder**? I

**Comment by ryanbourdais** [comment]
@skychiarottoa Have you tried adding `abd pull` to the parameter `post-emulator-launch-assemble-command`? This command will run after the emulator has been launched, and before commencing `wait-for-emulator`

**Comment by skychiarottoa** [comment]
I will try, but the command should be run after ui tests are run.

**Comment by skychiarottoa** [comment]
This is the output: 
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/51656240/181188744-e4201511-e0db-43e3-893d-2745fbf95545.png">

**Comment by ryanbourdais** [comment]
Hi @skychiarottoa, can you try splitting up `start-emulator-and-run-tests` ? All of the commands are in the orb, but you can run `create-avd` followed by `start-emulator` then `run-tests`, this will allow you to run any steps after `run-tests` that you please. The emulator will continue to run in background until `kill-emulators` is run.

**Comment by skychiarottoa** [comment]
Ok, I wanted to avoid this solution since it seem to me in contrast with the usefulness/goal of the orb. It allows to keep config.yml cleaner as possible.
It could be useful to add a parameter "adb_pull_destination_folder" to your command.
"adb pull" can be run inside you command  start-emulator-and-run-tests only if the parameter  "adb_pull_destination_folder" is set.

It very usefull and common to see app's screen shot attachments when a test fails.

Il will try your solution

thx

**Comment by JalexChen** [comment]
hi @skychiarottoa - were you able to get this working with @ryanbourdais suggestion? would love to hear back and include the pull destination folder parameter if this is the case

**Comment by skychiarottoa** [comment]
yes thx

**Comment by skychiarottoa** [comment]
Hi,
I can attach screenshot, but there are some problems since we are running our tests on  two parallel machines.

In detail we run out test in parallel on Machine 0 and Machine 1
When a test fail on **Machine 0**, in the associated "Artifact" tab we find a list of screenshots of test run of **Machine 1** but
in tab "Artifact" of machine 0 we expect screenshot of failed test run on machine 0.

Here some screen shots:
Running test on 2 machine, machine 1 has a failed test
<img width="649" alt="image" src="https://user-images.githubusercontent.com/51656240/184114175-76a8b944-9cbf-4aeb-834a-b468f403a92b.png">

Artifact Tab lists a succeded test of machine 0 instead of failed test on machine 1
<img width="937" alt="image" src="https://user-images.githubusercontent.com/51656240/184114401-04fdc3c8-1194-44c1-aa1c-3a9f20302150.png">
Note [app/screenshots/**EspressoFailedTestsScreenshots**/FaidateAttivitaTests00.kt-testTapAngelInConfirmData_1660145428333.jpeg](https://output.circle-artifacts.com/output/job/5245a177-127c-43c0-bbe7-817487f30775/artifacts/0/app/screenshots/EspressoFailedTestsScreenshots/FaidateAttivitaTests00.kt-testTapAngelInConfirmData_1660145428333.jpeg)

The failled test is:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/51656240/184115067-698ca3bb-eb2c-4f23-9a5e-72a45787d988.png">

Here the pipeline: https://app.circleci.com/pipelines/github/sky-uk/ita-app-myskyapp-android/15432/workflows/7dd949ab-c9d7-4aa2-b27d-4bce5b0e59e8

**Comment by skychiarottoa** [comment]
yes it works

**Comment by JalexChen** [comment]
Thanks for the update @skychiarottoa. Closing this issue out and creating a new one to add a pull destination folder parameter
