### ISSUE TITLE
How to run "adb shell settings put secure long_press_timeout 2000" before execution of test

### ISSUE THREAD

**Issue by skychiarottoa** [CircleCI-Public/android-orb#57]
I need to run the following

 "adb shell settings put secure long_press_timeout 2000"

before running the android test but I cannot find any example in the documentation of your orb

it is right the following conf:

![image](https://user-images.githubusercontent.com/51656240/193026149-277a8d89-0708-4d3d-9ea1-516ca77868c2.png)

**Comment by ryanbourdais** [comment]
Hi @skychiarottoa, are you trying to run this command as a prestep and then run the test? If so, there is no current way to do that, but I can start looking into adding that as a feature for the next minor release

**Comment by skychiarottoa** [comment]
Yes before running all ui tests.

**Comment by ryanbourdais** [comment]
Hi @skychiarottoa PR #67 adds a parameter to the `run-tests` command that will allow you to add a command before each test run. Once this PR is merged it should be added to the next release for this orb, which I plan on releasing by the end of this week
