### ISSUE TITLE
Trying to create AVD in the background results in failure

### ISSUE THREAD

**Issue by Nisim761** [CircleCI-Public/android-orb#63]
Orb version:
android: circleci/android@2.1.2

This is what i have in my config.file:
      - android/create-avd:
          system-image: "system-images;android-29;google_apis;x86"
          avd-name: Pixel_2_API_29
          install: true

Trying to add the background: true attribute to the step resulted with a failure when executing "circleci config validate", as follows, as the attribute is unnexpected:
https://discuss.circleci.com/t/create-avd-in-the-background/46840/2

**Comment by ryanbourdais** [comment]
Hi @Nisim761, I agree there should be the ability to run that command in background because it does cause a time sink. I just opened a PR that should move both steps of the `create-avd` command into 1 step and allow it to run with the `background` parameter as expected.

**Comment by Nisim761** [comment]
> Hi @Nisim761, I agree there should be the ability to run that command in background because it does cause a time sink. I just opened a [Pull Request](https://github.com/CircleCI-Public/android-orb/pull/65) that should move both steps of the `create-avd` command into 1 step and allow it to run with the `background` parameter as expected.

Thank you for implementing this so quickly. How can run the create-avd command in the background?
