### ISSUE TITLE
curl: (16) Error in the HTTP2 framing layer when installing NDK

### ISSUE THREAD

**Issue by ben-j69** [CircleCI-Public/android-orb#7]
### Orb version
circleci/android@0.2.1

### What happened

New issue appeared on Circle since few days when I install the NDK. This error is not always displayed, maybe 50% of our builds are concerned. I have tried the ndk r21d and the error is the same.

`  - android/install-ndk:
          ndk-version: android-ndk-r19c`

Error shown in circle 
`#!/bin/bash -eo pipefail
[ -w /usr/local/bin ] && SUDO="" || SUDO=sudo

$SUDO curl --silent --show-error --location --fail --retry 3 \
  --output /tmp/android-ndk-r19c.zip \
  https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip

$SUDO echo "fd94d0be6017c6acbd193eb95e09cf4b6f61b834 /tmp/android-ndk-r19c.zip" > /tmp/android-ndk-r19c.zip.sha1

sha1sum -c /tmp/android-ndk-r19c.zip.sha1

$SUDO unzip -q /tmp/android-ndk-r19c.zip -d /opt/android
$SUDO rm -f /tmp/android-ndk-r19c*

$SUDO chown -R circleci:circleci /opt/android/android-ndk-r19c

echo "export ANDROID_NDK_HOME=/opt/android/android-ndk-r19c" >> $BASH_ENV

if [[ -d /opt/android/android-ndk-r19c && \
  -n "$(ls -A /opt/android/android-ndk-r19c)" ]]; then
  echo "Android NDK installed"
else
  echo "Android NDK did not install successfully"
  exit 1
fi
curl: (16) Error in the HTTP2 framing layer

Exited with code exit status 16
CircleCI received exit code 16`

### Expected behavior
Should install the ndk as usual

**Comment by bvirlet** [comment]
Hello,

We are experiencing this problem as well, exactly the same symptoms.

Since about 24 hours, we started seeing failures in our builds with the following error:

> curl: (16) Error in the HTTP2 framing layer

Restarting the builds several times sometimes ended up in success => the issue seems to be sporadic.

The build script responsible for this problem is as follow:
```
#!/bin/bash -eo pipefail
[ -w /usr/local/bin ] && SUDO="" || SUDO=sudo

$SUDO curl --silent --show-error --location --fail --retry 3 \
--output /tmp/android-ndk-r21c.zip \
https://dl.google.com/android/repository/android-ndk-r21c-linux-x86_64.zip

$SUDO echo "c81a5bcb4672a18d3647bf6898cd4dbcb978d0e8 /tmp/android-ndk-r21c.zip" > /tmp/android-ndk-r21c.zip.sha1

sha1sum -c /tmp/android-ndk-r21c.zip.sha1

$SUDO unzip -q /tmp/android-ndk-r21c.zip -d /opt/android
$SUDO rm -f /tmp/android-ndk-r21c*

$SUDO chown -R circleci:circleci /opt/android/android-ndk-r21c

echo "export ANDROID_NDK_HOME=/opt/android/android-ndk-r21c" >> $BASH_ENV

if [[ -d /opt/android/android-ndk-r21c && \
-n "$(ls -A /opt/android/android-ndk-r21c)" ]]; then
echo "Android NDK installed"
else
echo "Android NDK did not install successfully"
exit 1
fi
```

I restarted the build with SSH, went and ran the curl command manually:
```
circleci@83ad7856c4d9:~$ sudo curl --show-error --location --fail --retry 3 --output /tmp/android-ndk-r21c.zip https://dl.google.com/android/repository/android-ndk-r21c-linux-x86_64.zip
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
76 1108M 76 849M 0 0 298M 0 0:00:03 0:00:02 0:00:01 298M
curl: (16) Error in the HTTP2 framing layer
```
This resulted in the same problem.

I tried wget, and it succeeded.
```
circleci@83ad7856c4d9:~$ wget https://dl.google.com/android/repository/android-ndk-r21c-linux-x86_64.zip
--2020-10-23 07:36:56-- https://dl.google.com/android/repository/android-ndk-r21c-linux-x86_64.zip
Resolving dl.google.com (dl.google.com)... 142.250.73.238, 2607:f8b0:4004:82a::200e
Connecting to dl.google.com (dl.google.com)|142.250.73.238|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1162375023 (1.1G) [application/zip]
Saving to: ‘android-ndk-r21c-linux-x86_64.zip.1’
```

I tried to update curl to the latest version, but it already seems to be up-to-date.

Retrying a couple times eventually succeeds.

Your help is appreciated!

**Comment by gmemstr** [comment]
Discussed this a little bit internally, and the closest issue I can find with curl is this: https://github.com/curl/curl/issues/3750. My thinking is that the curl version is indeed out of date in these images and needs to be updated, although it doesn't quite explain why it's happening _now_, which leads me to believe it's actually something on Google's end. Digging into this a little more and hope to have more to share soon.

**Comment by bvirlet** [comment]
Thanks @gmemstr. It's indeed possible that a change in the Google download server configuration triggered a specific bug in curl.
