### ISSUE TITLE
Using newer version of Android SDK causes emulator booting for too long

### ISSUE THREAD

**Issue by szymonrybczak** [CircleCI-Public/android-orb#81]
### Orb version
`circleci/android@2.3.0`
Config file: https://github.com/facebook/react-native/blob/600d1d4435869fb861cd8c28a685cac1b54eec11/.circleci/config.yml.
Job: `test_e2e_android`

### What happened
In React Native repository, we're implementing E2E tests, for this we need to launch Android emulator, the problem is when I try launching emulators with newer SDK the CI is booting emulator for too long. I tried with SDK 33, 32, 31, 30, see [here](https://app.circleci.com/pipelines/github/facebook/react-native/27333/workflows/cfa06af7-d1ee-415a-a3d5-dd5c3039bc7c/jobs/827263). It worked with SDK 29, but this is quite old and we wouldn't like to use it.

### Expected behavior

Booting emulator should not take so long.

**Comment by ryanbourdais** [comment]
Hi @szymonrybczak it seems like you are running this test with a 2 year old machine `2021.10.1`, have you tried updating this machine? Also, has this test only begun failing when you made the switch to `android@2.3.0` or is this entirely new behavior?

**Comment by szymonrybczak** [comment]
Hello @ryanbourdais, thanks for answering! 🙌 Yeah that's true, I switched to `2023.07.1` that is currently latest version and the emulators are now booting really fast :) PS. For me that was very confusing that in the docs you're using old machine, I just copy and paste from [docs](https://circleci.com/developer/orbs/orb/circleci/android). Maybe you can somehow dynamically update this?

I have one more question, after this change there is a [problem with JDK](https://app.circleci.com/pipelines/github/facebook/react-native/27423/workflows/99a59d44-8b8e-42eb-b89f-8f37aa16ebb1/jobs/832568). Based on that [post](https://discuss.circleci.com/t/android-images-july-update/48577) I can see that there's already installed JDK 17, so why there is problem with finding `java` executable? I tired setting environment variables (see [here](https://app.circleci.com/pipelines/github/facebook/react-native/27423/workflows/99a59d44-8b8e-42eb-b89f-8f37aa16ebb1/jobs/832568), `Set environment variables` step), but it isn't really working on new machine (on old machine it was working perfectly). Do you have any ideas how I can solve this issue? 🙏

**Comment by szymonrybczak** [comment]
So already I tried without these `update-alternative` lines, see [here](https://app.circleci.com/pipelines/github/facebook/react-native/27403/workflows/4faedc68-3304-4694-b506-1e0001fe3a70/jobs/831067) - it also unfortunately fails :(

**Comment by ryanbourdais** [comment]
Hi @szymonrybczak I ssh'd into a build of my own and I havent seen any issue with the java installation. I did notice [this line](https://app.circleci.com/pipelines/github/facebook/react-native/27403/workflows/4faedc68-3304-4694-b506-1e0001fe3a70/jobs/831067?invite=true#step-118-2757_131) which leads me to believe that your build requires java 11. You can you try using the `change-java-versions` to change to java 11 and see if this issue still affects you. Otherwise I would go to [this page](https://support.circleci.com/hc/en-us/requests/new) and open a support request.

**Comment by szymonrybczak** [comment]
Yeah, so I [tried](https://app.circleci.com/pipelines/github/facebook/react-native/27403/workflows/4faedc68-3304-4694-b506-1e0001fe3a70/jobs/831067?invite=true#step-118-2757_131) with Java 11, and as I though the build requires Java 17. Even invoking `change-java-versions` doesn't properly set the `java` executable for this build. Anyway thank you for help!
