### ISSUE TITLE
Android Gradle plugin requires Java 17 to run. You are currently using Java 11.

### ISSUE THREAD

**Issue by carlosjuarezflash** [CircleCI-Public/android-orb#82]
### Orb version
circleci/android@2.3.0

### What happened

We recently updated our android application and gradle project to use gradle 8.0, on our machines everything is working correctly, but while running the project in circleCI we are receiving that error. 

is there a way to add java 17 to the Android Orb machine? any plans to add java 17 by default?

* Where:
Build file '/home/circleci/project/app/build.gradle' line: 3

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 17 to run. You are currently using Java 11.
      Your current JDK is located in /usr/lib/jvm/java-11-openjdk-amd64
      You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

### Expected behavior

CircleCi could provide a new Android Orb Version with Java 17 for projects using gradle 8.0

**Comment by ryanbourdais** [comment]
Hi @carlosjuarezflash which image are you using for this project? We removed Java 11 in favor of java 17 in march, so all `cimg:android` versions `2023.03` or newer should have Java 17 packaged. Same goes for all machine images starting in March of this year.

**Comment by carlosjuarezflash** [comment]
@ryanbourdais Thanks for the clarification, you were right, the tag that i was using was an old one, i'm currently using 
tag: "2023.06.1"
and it worked correctly.

I must say though, finding the right machine and the characteristics it contains was a difficult task, 

the information here doesn't correspond 

https://circleci.com/developer/images/image/cimg/android#image-tags

with the tags shown in

https://circleci.com/developer/machine/image/android#image-tags

(and i accessed this page only through a URL found in a hidden reference of the executor in the documentation)
