### ISSUE TITLE
cgroup changed for latest orb version?

### ISSUE THREAD

**Issue by mpierucci** [CircleCI-Public/android-orb#83]
### Orb version
android@2.3.0

### What happened
When upgraded from 2.1.2 to 2.3.0, started seeing the following error:

`cat: /sys/fs/cgroup/memory/memory.max_usage_in_bytes: No such file or directory`

for my command
```

          name: Log memory usage
          command: cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes | awk -v var=" GB" '{printf $1/1000000000; printf var}'
```

[Link](https://app.circleci.com/pipelines/github/octoenergy/oes-field-services-app/6873/workflows/957b3397-dd95-4e3b-b451-be677e4ef1ac/jobs/11301)

### Expected behavior

Either keep working or documentation where cgroups changes is visibe?

**Comment by mpierucci** [comment]
Hi @ryanbourdais 

Yes, I also updated the ag from the  android/android-machine executor from `2021.10.1` to `2023.07.1`. Could it be related to that?

**Comment by ryanbourdais** [comment]
@mpierucci there have been alot of changes to the machine image in that time, I can't think of anything directly that would have changed this but you can [create a support ticket](https://support.circleci.com/hc/en-us/requests/new) for help with this issue.
