### ISSUE TITLE
Change java version overwrites PATH

### ISSUE THREAD

**Issue by maBarabas** [CircleCI-Public/android-orb#97]
### Orb version

2.5.0

### What happened

https://github.com/CircleCI-Public/android-orb/blob/7ef4c95a51d6f6efac356a50573545fd6b114bab/src/scripts/change-java-version.sh#L21

Evaluates $PATH at the time when the command runs, rather than when the bashrc is sourced. It will overwrite other changes to the PATH made in following steps. e.g. by the flutter orb.

Also I see that $BASH_ENV is recommended instead of ~/.bashrc in the docs.

It also evaluated JAVA_HOME at the wrong time which might explain #93.

**Comment by marboledacci** [comment]
This was solved in version [3.0.0](https://circleci.com/developer/orbs/orb/circleci/android?version=3.0.0)
